# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a2d33c046f45465e5f9de7246b50864b9aa893492052d7c6ea26320f484012c80b0e4e8325fc3d7421a04abe76d71c40191346a9f4afc671d0735d20ab33f6

test:
  secret_key_base: fcfa5bce18f02ee976ae28614bd0d01ebd04d20777411d815ff274b9d7fea623faa34bf9daa3f1abb45f13a5051091d4c83e60a99e18c8551e53f79935e1ecdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
